/**
 * Generated by apidoc - http://www.apidoc.me
 * Service version: 0.1.0-SNAPSHOT
 * apidoc:0.9.48 http://localhost:9000/movio/apidoc-generator-reference/0.1.0-SNAPSHOT/play_app_controllers
 */

package controllers

import javax.inject.Inject
import javax.inject.Singleton

import play.api.mvc._
import play.api.libs.json._

import scala.concurrent.duration._
import scala.util.{Success, Failure}

import services.HealthchecksService

class HealthchecksController @Singleton @Inject() (service: HealthchecksService) extends Controller {
  import movio.apidoc.generator.reference.v0.models._
  import movio.apidoc.generator.reference.v0.models.json._
  import play.api.libs.concurrent.Execution.Implicits.defaultContext
  
  def getInternalAndHealthcheck() = Action.async {  request =>
    service.get(request).map(_ match {
      case Success(result) =>
        Ok(Json.toJson(result))
      case Failure(ex) =>
        InternalServerError(Json.toJson(Error("500", ex.toString)))
    })
  }
}
