/**
 * Generated by apidoc - http://www.apidoc.me
 * Service version: 0.1.0-SNAPSHOT
 * apidoc:0.11.6 http://localhost:9000/movio/apidoc-generator-reference/0.1.0-SNAPSHOT/play_app_controllers
 */

package controllers

import javax.inject.Inject
import javax.inject.Singleton

import play.api.mvc._
import play.api.libs.json._

import scala.concurrent.duration._
import scala.concurrent.Future
import scala.util.{Success, Failure}

import services.PeopleService

class PeopleController @Singleton @Inject() (service: PeopleService) extends Controller {
  import movio.apidoc.generator.reference.v0.models._
  import movio.apidoc.generator.reference.v0.models.json._
  import play.api.libs.concurrent.Execution.Implicits.defaultContext
  
  def postV0AndPersonByTenant(
    tenant: String
  ) = Action.async(BodyParsers.parse.json) {  request =>
    request.body.validate[movio.apidoc.generator.reference.v0.models.Person] match {
      case errors: JsError =>
        errorResponse(errors, msg => Error("500", msg))
      case body: JsSuccess[movio.apidoc.generator.reference.v0.models.Person] =>
        service.post(request, body.get, tenant).map{_ match {
          case Success(result) =>
            Ok(Json.toJson(result))
          case Failure(ex) =>
            errorResponse(ex, msg => Error("500", msg))
        }}
    }
  }

  def postV0ByTenant(
    tenant: String
  ) = Action.async(BodyParsers.parse.json) {  request =>
    request.body.validate[Seq[movio.apidoc.generator.reference.v0.models.Person]] match {
      case errors: JsError =>
        errorResponse(errors, msg => Error("500", msg))
      case body: JsSuccess[Seq[movio.apidoc.generator.reference.v0.models.Person]] =>
        service.post(request, body.get, tenant).map{_ match {
          case Success(result) =>
            Ok(Json.toJson(result.size))
          case Failure(ex) =>
            errorResponse(ex, msg => Error("500", msg))
        }}
    }
  }

  private def errorResponse[A: Writes](errors: JsError, create: String => A): Future[Result] = {
    val msg = errors.errors.flatMap(node => {
      val nodeName = node._1.path.map(_.toString + ": ").mkString
      val message = node._2.map(_.message).mkString
      s"$nodeName$message"
    }).mkString
    scala.concurrent.Future(InternalServerError(Json.toJson(create(msg))))
  }

  private def errorResponse[A: Writes](ex: Throwable, create: String => A): Result =
    InternalServerError(Json.toJson(create(ex.getMessage)))

}
